version: '1.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    command: [ "yarn", "dev" ]

#ESTE ARCHIVO ES PARA USO DE LA APLICACION LOCAL EN DOCKER.COMPOSE USANDO LOS COMANDOS DE :
#COMANDO PARA EJECUTAR DOCKER.COMPOSE.YML
#docker-compose up --build
#llegando a conclusion que sirve para entorno de desarrollo en docker
